arb-dir: lib/l10n
template-arb-file: app_en.arb
output-class: S
output-localization-file: app_localizations.dart
output-dir: lib/l10n/generated
nullable-getter: false
synthetic-package: false
untranslated-messages-file: untranslated.txt
